size_t vs int64_t not decided, using int64_t for now
created being::being(optional being) ctor to pass to add(being) a being
and not an option being

all beings and fp added by value

using count_if to count alives

accumulate creates problem - not used
float sum_nutri(food_point const& lhs, food_point const& rhs) { return lhs.get_nutrival() + rhs.get_nutrival(); };
float tnutri = accumulate( creatures_.begin(), creatures_.end(), 0.0f, sum_nutri );
g++....
/usr/include/c++/4.6/bits/stl_numeric.h:155:2: error: invalid initialization of reference of type ‘const food_point&’ from expression of type ‘float’

first, last renamed to begin, end
i-> instead of (*i).

TO UNDERSTAND IF beings_end() CAN BE USED TO CONTROL THE FOR LOOP WHERE
BEINGS REPRODUCE - is it calculated at the beginning or moves during the loop?

now compiles, but not tested.